name: Sync data from mitre.org

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  "0 10 * * *"
  push:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Download mitre cvrf file
      uses: wei/wget@v1
      with:
        args: -O files/allitems-cvrf.xml https://cve.mitre.org/data/downloads/allitems-cvrf.xml
    - name: Download Redhat 4 rhsa file
      uses: wei/wget@v1
      with:
        args: -O 	files/com.redhat.rhsa-RHEL4.xml.bz2 https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL4.xml.bz2
    - name: Download Redhat 5 rhsa file
      uses: wei/wget@v1
      with:
        args: -O 	files/com.redhat.rhsa-RHEL5.xml.bz2 https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL5.xml.bz2
    - name: Download Redhat 6 rhsa file
      uses: wei/wget@v1
      with:
        args: -O 	files/com.redhat.rhsa-RHEL6.xml.bz2 https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL6.xml.bz2  
    - name: Download Redhat 7 rhsa file
      uses: wei/wget@v1
      with:
        args: -O 	files/com.redhat.rhsa-RHEL7.xml.bz2 https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml.bz2
    - name: Download Redhat 8 rhsa file
      uses: wei/wget@v1
      with:
        args: -O 	files/com.redhat.rhsa-RHEL8.xml.bz2 https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL8.xml.bz2     
    
    #- name: save
    #  uses: actions/upload-artifact@v2
    #  with:
    #      name: allitems file
    #      path: allitems-cvrf.xml
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/*
        tag: master
        overwrite: true
        file_glob: true
    # - name: Create Release
    #     id: create_release
    #     uses: actions/create-release@v1
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     with:
    #       tag_name: ${{ github.run_id }}
    #       release_name: Release ${{ github.ref }}
    #       draft: false
    #       prerelease: false
    # - name: Upload mitre cvrf Asset
    #   id: upload-mitre-cvrf-asset 
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
    #     asset_path: ./allitems-cvrf.xml
    #     asset_name: allitems-cvrf.xml
    #     asset_content_type: application/xml
    # - name: Upload Redhat 4 Asset
    #   id: upload-redhat4-asset 
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
    #     asset_path: ./com.redhat.rhsa-RHEL4.xml.bz2
    #     asset_name: com.redhat.rhsa-RHEL4.xml.bz2
    #     asset_content_type: application/x-bzip2
    # - name: Upload Redhat 5 Asset
    #   id: upload-redhat5-asset
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
    #     asset_path: ./com.redhat.rhsa-RHEL5.xml.bz2
    #     asset_name: com.redhat.rhsa-RHEL5.xml.bz2
    #     asset_content_type: application/x-bzip2
    # - name: Upload Redhat6 Asset
    #   id: upload-redhat6-asset
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
    #     asset_path: ./com.redhat.rhsa-RHEL6.xml.bz2
    #     asset_name: com.redhat.rhsa-RHEL6.xml.bz2
    #     asset_content_type: application/x-bzip2
    # - name: Upload Redhat7 Asset
    #   id: upload-redhat7-asset 
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
    #     asset_path: ./com.redhat.rhsa-RHEL7.xml.bz2
    #     asset_name: com.redhat.rhsa-RHEL7.xml.bz2
    #     asset_content_type: application/x-bzip2
    # - name: Upload Redhat8 Asset
    #   id: upload-redhat8-asset 
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
    #     asset_path: ./com.redhat.rhsa-RHEL8.xml.bz2
    #     asset_name: com.redhat.rhsa-RHEL8.xml.bz2
    #     asset_content_type: application/x-bzip2
