name: Sync data

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  "0 10 * * *"
  push:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Create dir
      run: mkdir files
    - name: Download mitre cvrf file
      uses: wei/wget@v1
      with:
        args: -O files/allitems-cvrf.xml https://cve.mitre.org/data/downloads/allitems-cvrf.xml
    - name: Download mitre cvrf gz file
      uses: wei/wget@v1
      with:
        args: -O files/allitems-cvrf.xml https://cve.mitre.org/data/downloads/allitems-cvrf.xml.gz
    - name: Download Redhat 4 rhsa file
      uses: wei/wget@v1
      with:
        args: -O    files/com.redhat.rhsa-RHEL4.xml.bz2 https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL4.xml.bz2
    - name: Download Redhat 5 rhsa file
      uses: wei/wget@v1
      with:
        args: -O    files/com.redhat.rhsa-RHEL5.xml.bz2 https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL5.xml.bz2
    - name: Download Redhat 6 rhsa file
      uses: wei/wget@v1
      with:
        args: -O    files/com.redhat.rhsa-RHEL6.xml.bz2 https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL6.xml.bz2  
    - name: Download Redhat 7 rhsa file
      uses: wei/wget@v1
      with:
        args: -O    files/com.redhat.rhsa-RHEL7.xml.bz2 https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml.bz2
    - name: Download Redhat 8 rhsa file
      uses: wei/wget@v1
      with:
        args: -O    files/com.redhat.rhsa-RHEL8.xml.bz2 https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL8.xml.bz2
    - name: Download nvdcve-1.1-2021.meta file
      uses: wei/wget@v1
      with:
        args: -O    files/nvdcve-1.1-2021.meta https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2021.meta
    - name: Download nvdcve-1.1-2020.meta file
      uses: wei/wget@v1
      with:
        args: -O    files/nvdcve-1.1-2020.meta https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2020.meta
    - name: Download vdcve-1.1-modified.meta file
      uses: wei/wget@v1
      with:
        args: -O    files/nvdcve-1.1-modified.meta https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta
    - name: Download nvdcve-1.1-recent.meta file
      uses: wei/wget@v1
      with:
        args: -O    files/nvdcve-1.1-recent.meta https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-recent.meta
    - name: Download nvdcve-1.1-2021.json.gz file
      uses: wei/wget@v1
      with:
        args: -O    files/nvdcve-1.1-2021.json.gz https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2021.json.gz
    - name: Download nvdcve-1.1-2020.json.gz file
      uses: wei/wget@v1
      with:
        args: -O    files/nvdcve-1.1-2020.json.gz https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2020.json.gz
    - name: Download vdcve-1.1-modified.json.gz file
      uses: wei/wget@v1
      with:
        args: -O    files/nvdcve-1.1-modified.json.gz https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.json.gz
    - name: Download nvdcve-1.1-recent.json.gz file
      uses: wei/wget@v1
      with:
        args: -O    files/nvdcve-1.1-recent.json.gz https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-recent.json.gz
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: files/*
        tag: upload
        overwrite: true
        file_glob: true
