name: Sync data from mitre.org

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  "*/15 * * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: download
      uses: wei/wget@v1
      with:
        args: -O allitems-cvrf.xml https://cve.mitre.org/data/downloads/allitems-cvrf.xml
    - name: save
      uses: actions/upload-artifact@v2
      with:
          name: allitems file
          path: data/allitems-cvrf.xml
