name: Sync data from mitre.org

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  "*/5 * * * *"
  push:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: download
      uses: wei/wget@v1
      with:
        args: -O allitems-cvrf.xml https://cve.mitre.org/data/downloads/allitems-cvrf.xml
    - name: save
      uses: actions/upload-artifact@v2
      with:
          name: allitems file
          path: allitems-cvrf.xml
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_id }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./allitems-cvrf.xml
        asset_name: allitems-cvrf.xml
        asset_content_type: application/xml
